# Generated by Django 5.1.7 on 2025-04-23 09:15

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalPost',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.post')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã kiểm duyệt'), ('rejected', 'Từ chối kiểm duyệt'), ('expired', 'Hết hạn'), ('rented', 'Đã thuê')], default='pending', max_length=10)),
                ('expired_date', models.DateTimeField(blank=True, default=posts.models.default_post_expiration_date, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('limit_person', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField()),
                ('number_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.IntegerField(blank=True, null=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(limit_choices_to={'status': 'approved'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('utilities', models.ManyToManyField(blank=True, related_name='rental_posts', to='posts.utilities')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSeekingPost',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.post')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã kiểm duyệt'), ('rejected', 'Từ chối kiểm duyệt'), ('expired', 'Hết hạn'), ('rented', 'Đã thuê')], default='pending', max_length=10)),
                ('expired_date', models.DateTimeField(blank=True, default=posts.models.default_post_expiration_date, null=True)),
                ('position', models.CharField(max_length=20)),
                ('area', models.FloatField()),
                ('limit_person', models.IntegerField()),
                ('tenent', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='room_seeking_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
