# Generated by Django 5.1.7 on 2025-04-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpost',
            name='comment_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentpost'),
        ),
        migrations.AlterField(
            model_name='roomseekingpost',
            name='comment_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentpost'),
        ),
    ]
