# Generated by Django 5.1.7 on 2025-04-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_imagepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostReference',
        ),
    ]
