# Generated by Django 5.1.7 on 2025-04-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_rentalpost_comment_post_and_more'),
        ('utils', '0006_delete_imagerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='utils.image'),
        ),
        migrations.AddField(
            model_name='roomseekingpost',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='utils.image'),
        ),
    ]
