# Generated by Django 5.1.7 on 2025-04-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rentalpost_images_roomseekingpost_images'),
        ('properties', '0002_property_delete_boardinghouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='address',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='comment_post',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='province',
        ),
        migrations.RemoveField(
            model_name='roomseekingpost',
            name='comment_post',
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='roomseekingpost',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
