# Generated by Django 5.1.7 on 2025-04-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_rentalpost_address_remove_rentalpost_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='property',
        ),
        migrations.RemoveField(
            model_name='roomseekingpost',
            name='property',
        ),
    ]
