# Generated by Django 5.1.7 on 2025-05-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalpost',
            old_name='landlord',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='roomseekingpost',
            old_name='tenant',
            new_name='owner',
        ),
    ]
