# Generated by Django 5.1.7 on 2025-04-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_rentalpost_property_and_more'),
        ('properties', '0002_property_delete_boardinghouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
