# Generated by Django 5.1.7 on 2025-06-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_landlord_rentalpost_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
