# Generated by Django 5.1.7 on 2025-06-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('posts', '0005_rename_landlord_rentalpost_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomseekingpost',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomseekingpost', to='locations.district'),
        ),
        migrations.AddField(
            model_name='roomseekingpost',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomseekingpost', to='locations.province'),
        ),
    ]
