# Generated by Django 5.1.7 on 2025-04-21 11:47

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rentalpost_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=posts.models.default_post_expiration_date, null=True),
        ),
        migrations.AddField(
            model_name='roomseekingpost',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=posts.models.default_post_expiration_date, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã kiểm duyệt'), ('rejected', 'Từ chối kiểm duyệt'), ('expired', 'Hết hạn'), ('rented', 'Đã thuê')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomseekingpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã kiểm duyệt'), ('rejected', 'Từ chối kiểm duyệt'), ('expired', 'Hết hạn'), ('rented', 'Đã thuê')], default='pending', max_length=10),
        ),
    ]
