# Generated by Django 5.1.7 on 2025-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_roomseekingpost_district_roomseekingpost_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomseekingpost',
            name='price_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomseekingpost',
            name='price_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
