# Generated by Django 5.1.7 on 2025-04-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rentalpost_expired_date_roomseekingpost_expired_date_and_more'),
        ('properties', '0003_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpost',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='property',
            field=models.ForeignKey(limit_choices_to={'status': 'approved'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomseekingpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomseekingpost',
            name='tenent',
            field=models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='room_seeking_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
