# Generated by Django 5.1.7 on 2025-06-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_roomseekingpost_price_max_roomseekingpost_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
