# Generated by Django 5.1.7 on 2025-06-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_utilities_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpost',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('rejected', 'Từ chối kiểm duyệt'), ('expired', 'Hết hạn'), ('rented', 'Đã thuê')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomseekingpost',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('rejected', 'Từ chối kiểm duyệt'), ('expired', 'Hết hạn'), ('rented', 'Đã thuê')], default='active', max_length=10),
        ),
    ]
