# Generated by Django 5.1.7 on 2025-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_utilities_rentalpost_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pd', 'Đang kiểm duyệt'), ('ap', 'Đã kiểm duyệt'), ('rj', 'Từ chối kiểm duyệt'), ('ep', 'Hết hạn'), ('rt', 'Đã thuê')], default='pd', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('LR', 'Landlord'), ('TN', 'Tenant')], default='TN', max_length=10),
        ),
    ]
