# Generated by Django 5.1.7 on 2025-03-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_composation_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Composation',
            new_name='Conversation',
        ),
    ]
