# Generated by Django 5.1.7 on 2025-03-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_conversation_landlord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'user_type': 'LR'}, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tenent',
            field=models.ForeignKey(limit_choices_to={'user_type': 'TN'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='core.image')),
            ],
            options={
                'db_table': 'image_relation',
            },
        ),
        migrations.DeleteModel(
            name='RoomSeekingPost',
        ),
    ]
