# Generated by Django 5.1.7 on 2025-03-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.commentpost'),
        ),
    ]
