# Generated by Django 5.1.7 on 2025-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('landlord', 'Chủ nhà'), ('tenant', 'Người thuê')], default='tenant', max_length=10),
        ),
    ]
