# Generated by Django 5.1.7 on 2025-04-23 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('district', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('images', models.ManyToManyField(blank=True, related_name='%(class)s', to='utils.image')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
