# Generated by Django 5.1.7 on 2025-04-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
    ]
