# Generated by Django 5.1.7 on 2025-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_delete_boardinghouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang kiểm duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=10),
        ),
    ]
