# Generated by Django 5.1.7 on 2025-04-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_images_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='properties_name',
            new_name='name',
        ),
    ]
