INSERT INTO posts_utilities (active, created_date, updated_date, name, icon) VALUES
(1, NOW(), NOW(), 'Wifi', 'wifi'),
(1, NOW(), NOW(), 'Nước nóng lạnh', 'water-boiler'),
(1, NOW(), NOW(), 'Tủ lạnh', 'fridge'),
(1, NOW(), NOW(), 'Máy giặt', 'washing-machine'),
(1, NOW(), NOW(), 'Hồ bơi', 'pool'),
(1, NOW(), NOW(), 'Máy lạnh', 'air-conditioner'),
(1, NOW(), NOW(), 'Bãi đậu xe hơi', 'car-parking-lights'),
(1, NOW(), NOW(), 'Chỗ để xe máy', 'motorbike'),
(1, NOW(), NOW(), 'Thang máy', 'elevator'),
(1, NOW(), NOW(), 'Ban công', 'balcony'),
(1, NOW(), NOW(), 'Bảo vệ 24/7', 'security'),
(1, NOW(), NOW(), 'Camera giám sát', 'cctv'),
(1, NOW(), NOW(), 'Khu vực BBQ', 'grill'),
(1, NOW(), NOW(), 'Phòng gym', 'dumbbell'),
(1, NOW(), NOW(), 'Sân vườn', 'flower'),
(1, NOW(), NOW(), 'Máy nước lọc', 'water-pump'),
(1, NOW(), NOW(), 'Máy hút mùi', 'toaster-oven'),
(1, NOW(), NOW(), 'Máy rửa chén', 'dishwasher'),
(1, NOW(), NOW(), 'Cửa sổ lớn', 'window-open'),
(1, NOW(), NOW(), 'Gần siêu thị', 'cart'),
(1, NOW(), NOW(), 'Gần trường học', 'school'),
(1, NOW(), NOW(), 'Gần bến xe buýt', 'bus-stop'),
(1, NOW(), NOW(), 'Gần trạm MRT', 'train-variant'),
(1, NOW(), NOW(), 'Đầy đủ nội thất', 'sofa'),
(1, NOW(), NOW(), 'Cho phép nuôi thú cưng', 'dog'),
(1, NOW(), NOW(), 'Hệ thống chữa cháy', 'fire-extinguisher'),
(1, NOW(), NOW(), 'Đồng hồ điện riêng', 'flash'),
(1, NOW(), NOW(), 'Đồng hồ nước riêng', 'water'),
(1, NOW(), NOW(), 'Internet tốc độ cao', 'lan-connect'),
(1, NOW(), NOW(), 'Hầm chứa đồ', 'warehouse');
