"""
Django settings for renthub project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

import cloudinary
import cloudinary.uploader
import pymysql
from dotenv import load_dotenv

from django.templatetags.static import static

# Dùng để tạo đường dẫn trong django unfold sidebar
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Load .env file for API key
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '10.17.64.127',  # Android Emulator
    "localhost",
    "127.0.0.1",
    ".vercel.app",
    "renthub.up.railway.app",
    "192.168.1.10",
]

CSRF_TRUSTED_ORIGINS = ["https://renthub.up.railway.app"]

# Application definition

INSTALLED_APPS = [
    # Django unfold
    "unfold",
    "unfold.contrib.filters",  # Bộ lọc nâng cao (không bắt buộc)
    "unfold.contrib.forms",  # Form nâng cao (không bắt buộc)
    # Các App cấu hình Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Các App ngoài bổ sung
    "drf_yasg",
    "rest_framework",
    "debug_toolbar",
    "oauth2_provider",
    # "corsheaders",
    # Các App của Renthub
    "admin_site.apps.AdminSiteConfig",
    "utils.apps.UtilsConfig",
    "accounts.apps.AccountsConfig",
    "posts.apps.PostsConfig",
    "properties.apps.PropertiesConfig",
    "comments.apps.CommentsConfig",
    "chats.apps.ChatsConfig",
    "locations.apps.LocationsConfig",
    # Test app
    "testing.apps.TestingConfig",
]

CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware', # White noise
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # Debug Toolbar
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "renthub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "renthub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

pymysql.install_as_MySQLdb()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Đường dẫn đến thư mục static của dự án
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DRF Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ],
}



# Configuration for Cloudinary
cloudinary.config(
    cloud_name="dmt4mvjdx",
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

# Configuration for Google Maps API
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

# Thiết lập địa chỉ IP cho Debug Toolbar, chỉ cho phép truy cập
# vào debug toolbar ở địa chỉ localhost

INTERNAL_IPS = ["127.0.0.1", "10.0.2.2","192.168.1.10"]

# JWT Configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

OAUTH2_PROVIDER = {
    "SCOPES": {"read": "Read scope", "write": "Write scope"},
    "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
    "GRANT_TYPES": ["password", "refresh_token", "authorization_code"],
}


CLIENT_ID = os.getenv("OATUH2_CLIENT_ID")
CLIENT_SECRET = os.getenv("OATUH2_CLIENT_SECRET")

UNFOLD = {
    "SITE_TITLE": "Renthub Admin",
    "SITE_HEADER": "Renthub",
    "SITE_URL": "/",
    "SITE_ICON": None,  # Đường dẫn đến icon của bạn nếu có
    # Cấu hình thanh bên - sidebar
    "SIDEBAR": {
        "navigation": [
            {
                "title": _("Home"),
                "icon": "home",
                "items": [
                    {
                        "icon": "apps",
                        "title": _("All applications"),
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("User Manager"),
                "separator": True,
                "items": [
                    {
                        "icon": "person",
                        "title": _("Users"),
                        "link": reverse_lazy("renthub_admin:accounts_user_changelist"),
                    },
                    {
                        "icon": "person_add",
                        "title": _("Landlords Approval"),
                        "link": reverse_lazy(
                            "renthub_admin:accounts_landlordapproved_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Post Manager"),
                "separator": True,
                "items": [
                    {
                        "icon": "news",
                        "title": _("Rentals posts"),
                        "link": reverse_lazy(
                            "renthub_admin:posts_rentalpost_changelist"
                        ),
                    },
                    {
                        "icon": "travel_explore",
                        "title": _("Room seeking posts"),
                        "link": reverse_lazy(
                            "renthub_admin:posts_roomseekingpost_changelist"
                        ),
                    },
                ],
            },
            {
                "separator": True,
                "items": [
                    {
                        "icon": "real_estate_agent",
                        "title": _("Property"),
                        "link": reverse_lazy(
                            "renthub_admin:properties_property_changelist"
                        ),
                    },
                ],
            },
        ],
    },
    "STYLES": [
        lambda request: static("css/styles.css"),
    ],
    "COLORS": {
        "base": {
            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "209 213 219",
            "400": "156 163 175",
            "500": "107 114 128",
            "600": "75 85 99",
            "700": "55 65 81",
            "800": "31 41 55",
            "900": "17 24 39",
            "950": "3 7 18",
        },
        "primary": {
            "50": "250 245 255",
            "100": "206 250 254",
            "200": "162 244 253",
            "300": "83 234 253",
            "400": "0 211 242",
            "500": "0 184 219",
            "600": "0 146 184",
            "700": "0 117 149",
            "800": "0 95 120",
            "900": "16 78 100",
            "950": "5 51 69",
        },
    },
}
