# Generated by Django 5.1.7 on 2025-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomseekingpost',
            name='comment_post',
        ),
        migrations.RemoveField(
            model_name='roomseekingpost',
            name='tenent',
        ),
        migrations.DeleteModel(
            name='RentalPost',
        ),
        migrations.DeleteModel(
            name='Utilities',
        ),
        migrations.DeleteModel(
            name='RoomSeekingPost',
        ),
    ]
