# Generated by Django 5.1.7 on 2025-04-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_remove_roomseekingpost_comment_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardingHouse',
        ),
    ]
