# Generated by Django 5.1.7 on 2025-04-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_rentalpost_comment_post_and_more'),
        ('utils', '0003_delete_boardinghouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
