# Generated by Django 5.1.7 on 2025-04-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_remove_comment_post_remove_comment_reply_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='composation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
