# Generated by Django 5.1.7 on 2025-04-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_message_composation_delete_conversation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageRelation',
        ),
    ]
